# -*- coding: utf-8 -*-
"""Flask Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLwR00_p_Brx-DiRoSAebCLdAmmfDKms
"""

from flask import Flask, request, jsonify

app = Flask(TechnicalAssignment1_SIC)

@app.route('/data', methods=['POST'])
def receive_data():
    data = request.json
    if not data:
        return jsonify({"error": "No data received"}), 400

    temperature = data.get('temperature')
    humidity = data.get('humidity')

    if temperature is None or humidity is None:
        return jsonify({"error": "Incomplete data"}), 400

    print(f"Received data - Temperature: {temperature}, Humidity: {humidity}")

    return jsonify({"status": "success", "temperature": temperature, "humidity": humidity}), 200

if __name__ == '__main__':
    app.run(host='CONFIDENTIAL', port=CONFIDENTIAL)